# Generated by Django 4.2 on 2023-05-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
